### PR TITLE
Update to vis.js 4.16.1

### PR DESCRIPTION
**Pull request by jspanjers**

### CODE REVIEW

**Comment by luciuschoi** [comment]
Thank you.

**Comment by jspanjers** [comment]
Thank you for merging this! Can you publish a new release on rubygems?

**Comment by luciuschoi** [comment]
Yep!

Lucius Choi
1. 8. 1. 오후 5:13 Jan-Joost Spanjers notifications@github.com 작성:

**Comment by jspanjers** [comment]
I do not see the new release on rubygems yet. Did something go wrong?

**Comment by jspanjers** [comment]
There is still no release on rubygems yet. I would really like to use a released version. Can I help you with publishing it?

**Comment by luciuschoi** [comment]
Sorry too late.
I just tried to release its new version to Rubygems.org but unfortunately, they are now in progress  of database maintenance. ^^ 
After that, I'll try again. Thank you.

**Comment by luciuschoi** [comment]
Mission completed! 
https://rubygems.org/gems/visjs-rails

**Pull request merged**
